### ISSUE TITLE
Timestamps fail to decode due to microseconds.

### ISSUE THREAD

**Issue by ceedon** [lpil/pog#41]
Common pg built-ins like `now()` add microseconds.
This causes decode_timestamp https://github.com/lpil/pgo/blob/3c7926125ff3050c1ac378eede6513762e0c0571/src/gleam/pgo.gleam#L531 to error as it's expecting `#(#(Int, Int, Int), #(Int, Int, Int))` and receives `#(#(Int, Int, Int), #(Int, Int, Float))`.

Is this intentional?
Feels like changing the last element to a Float would work in both cases.

**Comment by lpil** [comment]
Hello! We've been having some discussion to determine what to do about this, and with time types in general. Sorry about the problem

**Comment by ceedon** [comment]
Yeah, plenty of ways around it. Made the magic of squirrel decidedly less magical is all!
Thanks for taking a look.

**Comment by giacomocavalieri** [comment]
This should be fixed now that pot has its own time type with microseconds!

**Comment by ceedon** [comment]
Neat! I'll play guinea pig tonight.

**Comment by lpil** [comment]
Thanks folks!
